program: run_iql.py
name: train_size_exp_iql
project: lhd-orl
method: grid
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--data"
  - "data/rb_1000_20221118T0816.pkl"
  - "--n_epochs"
  - "50"
  - ${args}
parameters:
  test_size:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]