program: run_awac.py
name: train_size_exp_awac
project: lhd-orl
method: grid
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--data"
  - "data/rb_1000_20221118T0816.pkl"
  - "--n_epochs"
  - "20"
  - ${args}
parameters:
  test_size:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]